### ISSUE TITLE
`import.meta.url` as URL instead of string

### ISSUE THREAD

**Issue by ravinggenius** [tc39/proposal-import-meta#13]
Shouldn't `import.meta.url` be an instance of URL? As a string it requires some manipulation to for instance mimic Node's `__filename`:

```javascript
const __filename = import.meta.url.replace(/^file:\/\//', '');
```

whereas a URL object is a richer datatype and can be used as is.

SEE https://github.com/nodejs/node/issues/20357

**Comment by domenic** [comment]
https://url.spec.whatwg.org/#url-apis-elsewhere
