### ISSUE TITLE
Stage 4 eligibility requirements

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-import-meta#17]
It'd be great to have an issue tracking those requirements:
 - [x] test262 tests merged (https://github.com/tc39/test262/pull/1888)
 - [x] sufficient implementations shipped stable
    - [x] jsc
    - [x] qjs
    - [x] sm
    - [x] v8/chrome/node
    - [x] xs
    - [x] babel
    - [x] engine262 (flag)
    - [ ] webpack
    - [ ] browserify
    - [x] rollup
 - [ ] significant in-the-field experience
 - [x] a PR is opened to the spec: https://github.com/tc39/ecma262/pull/1892
 - [x] that PR has been approved by the editors

**Comment by devsnek** [comment]
jsc, qjs, sm, v8, xs, ch: shipping without flags
engine262: behind a flag, but stable

side question: does anyone actually implement both HostGetImportMetaProperties and HostFinalizeImportMeta?

**Comment by MylesBorins** [comment]
We did it!
