### ISSUE TITLE
Get reviews

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-import-meta#2]
TC39-appointed reviewers:

- [x] @ajklein
- [x] @dherman 
- [x] @wycats 

Also the editor:

- [x] @bterlson

**Comment by dmitriid** [comment]
Why do you insist on randomly overloading language keywords with random things for your own pleasure?

First, let's make `import` a not-really-a-keyword-not-really-a-function abomination.

Now let's randomly add properties to it. Because reasons. What happened to sitting down and speccing out and designing things?

**Comment by domenic** [comment]
I've deleted a comment that was off-topic for this thread (and fairly disrespectful, to boot). Looking forward to getting reviews for this feature.

**Comment by dmitriid** [comment]
I realize that community input means next to nothing. Still, it would be really nice to hear the reaons for this, why it's already stage 2, and what's the rationale behind randomly extending keywords with random properties

**Comment by dmitriid** [comment]
Getting accepted in stage 1 and moving to stage 2 means:

> The committee expects to devote time to examining the problem space, solutions and cross-cutting concerns

So. Problem space is defined. There are concerns. How are they going to be addressed?

**Comment by domenic** [comment]
I'm deleting more off-topic comments from @dmitriid, as he does not seem to understand this is a thread dedicated to getting reviews from the TC39-appointed reviewers. There is a whole repository open for other technical issues with this specification, and no need to derail the reviewer thread.

@dmitriid, please email es-discuss with your question, as it is off-topic for this repository  (which builds on established precedent like new.target, super.*, function.sent, etc.) and are about more general issues.

I guess I'll lock this thread as it seems to be attracting more off-topic noise and the reviewers will have comment privileges anyway.

**Comment by dherman** [comment]
:+1:

**Comment by domenic** [comment]
All done, stage 3, woo!! @bterlson, you mentioned some editorial issues, please feel free to file :)
