### ISSUE TITLE
Irrelevant? - ESLINT considers import a keyword

### ISSUE THREAD

**Issue by Lonniebiz** [tc39/proposal-import-meta#22]
Should `import.meta` be `somethingElse.meta`?

Look at the issue I'm having with ESLINT:
https://stackoverflow.com/questions/54337576/

And look at this discussion regarding the matter:
https://github.com/eslint/eslint/issues/11514

To me, it seems like eslint shouldn't consider `import.` (notice the dot) the same thing as `import`. They won't address the matter until import.meta reaches stage 4.

I'm not posting here trying to get you to fix ESLINT. I'm posting here because I thought the issue might be relevant in some way to the import.meta project.

Could naming this object `import` be problematic to other things (beyond linters that won't yet support `import.meta`)?

There's `import`, `import()`, and `import.meta`. Maybe all that use of the word "import" for 3 separate things is just fine, but I'm reporting anyway, just in case it is something that should be taken into consideration. Thanks.

**Comment by MylesBorins** [comment]
@Lonniebiz the proposal is stage 4 and there is an active issue tracking proper integration into eslint. Until that lands you can use the babel-eslint parser to get support

https://github.com/eslint/eslint/issues/13133
